name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-18.04
    steps:
      - uses: release-drafter/release-drafter@v5.13.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
